### PR TITLE
Own namespace for batman-adv-legacy

### PR DESCRIPTION
**Pull request by T-X**
With this patchset it is possible to run both batman-adv and batman-adv-legacy on the same host. If that makes sense, I can work on making a batctl-legacy and updating OpenWRT packages, too.

### CODE REVIEW

**Comment by NeoRaider** [comment]
Some comments:

* I'd prefer to have all symbols, defines, structs, everything, renamed to batadv_legacy_...
* The debugfs directory will need to be renamed as well, otherwise removing one batman-adv module will also remove the other's debugfs tree in `batadv_debugfs_destroy`

**Comment by T-X** [comment]
The debugfs, good point, forgot about that, thanks!

For the symbols, I'm currently undecisive. I tried building both batman-adv and batman-adv-legacy as kernel built-ins and yes, that will fail with duplicate names for non-static functions. On the other hand, we don't want to get batman-adv-legacy upstream and I don't know of anyone using or wanting to use batman-adv-legacy as a kernel built-in. As mentioned yesterday, renaming all structs and functions would make it more difficult to cherry-pick patches from upstream. And it will need quite some effort if we'd want to keep kernel-style compliance (e.g. alignment, max. 80 chars per line). Not sure whether that'd be worth the effort. Maybe we could postpone the renaming until someone asks for / needs kernel built-in support for batman-adv-legacy?

**Comment by T-X** [comment]
Added a patch for the debugfs namespace change. Let me know whether this patchset seems fine for you now or not.

**Comment by NeoRaider** [comment]
I'd really like to have the symbol name changed, too.

I don't think we have a reason to care about the 80 char limit, everything seems to be fixable. Unfortunately, when running a recent checkpatch version, batman-adv-legacy yields hundreds of errors and warnings, so I'm currently pondering if fixing it all up would be worth the effort.

As the current batman-adv master is mostly checkpatch-clean, it would reduce the differences between the versions and thus probably make backports easier...

Anyways, it's really an independent problem, so I'll review the changes a bit more and merge this then.

**Comment by hwhw** [comment]
Been there, done that: https://github.com/hwhw/batman-adv-legacy/tree/versioned - though working (tested running side-to-side with batman-v15), I don't see much gain in this. What is the target? Gateways? That would probably the one place where one could reasonably use this. The main culprit is that a network device can only have a single "master", so it's either v14 or v15 on an interface anyway. I tricked around this restriction by using the "veth" interfaces, which can be used like a bridge of two virtual interfaces without actually being a bridge. Using that and a bridge, one can run v14 and v15 on the same interface (been there, done that). BUT: without further patching, this will not work on adhoc Wifi interfaces because with that horrid hack there's still about 2 or 3 different MAC addresses in use.

As for running both protocols on the same machine, I found it considerably easier to run usermode linux (UML) instances - thus doing batman-adv routing in usermode, sort of. If anyone is interested, this is my mini-instance build environment: https://github.com/hwhw/usermode-batman-adv

**Comment by T-X** [comment]
@hwhw: Do you want to rebase your branch and make a new pull-request then?

Regarding checkpatch and alignments, what do you guys think about changing "batadv_" prefixes to "batleg_" or "batadl_", so keeping it at 6 characters? And batman-adv module and sysfs names which do not have any length issues but are viewable from userspace to the full length batman-adv-legacy?

**Comment by NeoRaider** [comment]
I agree with @hwhw, there's no point in the renaming. We should finally build the a better autoupdater for Gluon, and let batman-adv-legacy die for good.

**Pull request closed without merging**
